ScoreTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

crm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('golf_course_list', views.golf_course_list, name='golf_course_list'),
    path('golf_course/<int:pk>/edit/', views.golf_course_edit, name='golf_course_edit'),
    path('golf_course/<int:pk>/delete/', views.golf_course_delete, name='golf_course_delete'),
    path('golf_course/create/', views.golf_course_new, name='golf_course_new'),
    path('score_list', views.score_list, name='score_list'),
    path('score/<int:pk>/edit/', views.score_edit, name='score_edit'),
    path('score/<int:pk>/delete/', views.score_delete, name='score_delete'),
    path('score/create/', views.score_new, name='score_new'),
    path('golf_course/<int:pk>/score_compare/', views.score_compare, name='score_compare'),
]

crm/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class GolfCourse(models.Model):
    course_name = models.CharField(max_length=50)
    hole_one_par = models.IntegerField()
    hole_two_par = models.IntegerField()
    hole_three_par = models.IntegerField()
    hole_four_par = models.IntegerField()
    hole_five_par = models.IntegerField()
    hole_six_par = models.IntegerField()
    hole_seven_par = models.IntegerField()
    hole_eight_par = models.IntegerField()
    hole_nine_par = models.IntegerField()
    hole_ten_par = models.IntegerField()
    hole_eleven_par = models.IntegerField()
    hole_twelve_par = models.IntegerField()
    hole_thirteen_par = models.IntegerField()
    hole_fourteen_par = models.IntegerField()
    hole_fifteen_par = models.IntegerField()
    hole_sixteen_par = models.IntegerField()
    hole_seventeen_par = models.IntegerField()
    hole_eighteen_par = models.IntegerField()
    total_par = models.IntegerField()
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
       return str(self.course_name)

class Score(models.Model):
    course_name = models.ForeignKey(GolfCourse, on_delete=models.CASCADE, related_name='score')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hole_one = models.IntegerField()
    hole_two = models.IntegerField()
    hole_three = models.IntegerField()
    hole_four = models.IntegerField()
    hole_five = models.IntegerField()
    hole_six = models.IntegerField()
    hole_seven = models.IntegerField()
    hole_eight = models.IntegerField()
    hole_nine = models.IntegerField()
    hole_ten = models.IntegerField()
    hole_eleven = models.IntegerField()
    hole_twelve = models.IntegerField()
    hole_thirteen = models.IntegerField()
    hole_fourteen = models.IntegerField()
    hole_fifteen = models.IntegerField()
    hole_sixteen = models.IntegerField()
    hole_seventeen = models.IntegerField()
    hole_eighteen = models.IntegerField()
    total_score = models.IntegerField()
    golf_date=models.DateField()
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.course_name)

crm/forms.py
from django import forms
from .models import GolfCourse, Score
from django.forms import ModelForm


class DateInput(forms.DateInput):
    input_type = 'date'

class GolfCourseForm(forms.ModelForm):
    class Meta:
        model = GolfCourse
        fields = ( 'course_name',
    'hole_one_par',
    'hole_two_par',
    'hole_three_par',
    'hole_four_par',
    'hole_five_par',
    'hole_six_par',
    'hole_seven_par',
    'hole_eight_par',
    'hole_nine_par',
    'hole_ten_par',
    'hole_eleven_par',
    'hole_twelve_par',
    'hole_thirteen_par',
    'hole_fourteen_par',
    'hole_fifteen_par',
    'hole_sixteen_par',
    'hole_seventeen_par',
    'hole_eighteen_par',
    'total_par')

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ( 'course_name', 'user',
    'hole_one',
    'hole_two',
    'hole_three',
    'hole_four',
    'hole_five',
    'hole_six',
    'hole_seven',
    'hole_eight',
    'hole_nine',
    'hole_ten',
    'hole_eleven',
    'hole_twelve',
    'hole_thirteen',
    'hole_fourteen',
    'hole_fifteen',
    'hole_sixteen',
    'hole_seventeen',
    'hole_eighteen',
    'total_score',
    'golf_date' ,)
        widgets = { 'golf_date': DateInput()}

crm/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from .models import *
from .forms import *

now = timezone.now()
def home(request):
   return render(request, 'crm/home.html',
                 {'crm': home})

@login_required
def golf_course_list(request):
    course = GolfCourse.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/golf_course_list.html',
                 {'courses': course})

@login_required
def golf_course_edit(request, pk):
   course = get_object_or_404(GolfCourse, pk=pk)
   if request.method == "POST":
       # update
       form = GolfCourseForm(request.POST, instance=course)
       if form.is_valid():
           course = form.save(commit=False)
           course.updated_date = timezone.now()
           course.save()
           course = GolfCourse.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/golf_course_list.html',
                         {'courses': course})
   else:
        # edit
       form = GolfCourseForm(instance=course)
   return render(request, 'crm/golf_course_edit.html', {'form': form})

@login_required
def golf_course_delete(request, pk):
   course = get_object_or_404(GolfCourse, pk=pk)
   course.delete()
   return redirect('crm:golf_course_list')

@login_required
def golf_course_new(request):
    if request.method == "POST":
        form = GolfCourseForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.created_date = timezone.now()
            course.save()
            courses = GolfCourse.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/golf_course_list.html',
                {'courses': courses})
    else:
        form = GolfCourseForm()
        # print("Else")
    return render(request, 'crm/golf_course_new.html', {'form': form})

@login_required
def score_list(request):
    score = Score.objects.filter(created_date__lte=timezone.now(), user__username=request.user)
    return render(request, 'crm/score_list.html',
                 {'scores': score})

@login_required
def score_edit(request, pk):
   score = get_object_or_404(Score, pk=pk)
   if request.method == "POST":
       # update
       form = ScoreForm(request.POST, instance=score)
       if form.is_valid():
           score = form.save(commit=False)
           score.updated_date = timezone.now()
           score.save()
           score = Score.objects.filter(created_date__lte=timezone.now())
           return render(request, 'crm/score_list.html',
                         {'scores': score})
   else:
        # edit
       form = ScoreForm(instance=score)
   return render(request, 'crm/score_edit.html', {'form': form})

@login_required
def score_delete(request, pk):
   score = get_object_or_404(Score, pk=pk)
   score.delete()
   return redirect('crm:score_list')

@login_required
def score_new(request):
    if request.method == "POST":
        form = ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            score.created_date = timezone.now()
            score.save()
            scores = Score.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/score_list.html',
                {'scores': scores})
    else:
        form = ScoreForm()
        # print("Else")
    return render(request, 'crm/score_new.html', {'form': form})

@login_required
def score_compare(request, pk):
    course = get_object_or_404(GolfCourse, pk=pk)
    courses = GolfCourse.objects.filter(created_date__lte=timezone.now())
    #customer = get_object_or_404(Customer, pk=pk)
    #customers = Customer.objects.filter(created_date__lte=timezone.now())
    #services = Service.objects.filter(cust_name=pk)
    #products = Product.objects.filter(cust_name=pk)
    scores = Score.objects.filter(course_name = pk)
    #scores = Score.objects.filter(course_name__pk=pk)
    return render(request, 'crm/score_compare.html', {'scores': scores, 'courses':courses})

crm/templates/crm/base.html
{% load static %}

<html lang="en">
<head>
    <title>Frenemies ScoreTracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Frenemies ScoreTracker
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'crm:home' %}">Home</a></li>
                <li><a href="{% url 'crm:golf_course_list' %}">Golf Courses</a></li>
               <li><a href="{% url 'crm:score_list' %}">My Scores</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/Course_photo.jpg" %}" alt="course_photo"/>
                                <div class="caption">
                                    <h2>Golf Courses</h2>
                                    <p>Courses utilized by Frenemies</p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'crm:golf_course_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/scorecard.jpg" %}" alt="scorecard"/>
                                <div class="caption">
                                    <h2>My Scores</h2>
                                    <p>Less is more!</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:score_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

crm/templates/crm/golf_course_delete.html
{% extends 'crm/base.html' %}
{% block body_block %}
    <h1>Delete {{ course.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=course.course_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/golf_course_edit.html
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Golf Course</h1>
    <form method="POST" class="course-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

crm/templates/crm/golf_course_list.html
   {% extends 'crm/base.html' %}
   {% load filters %}
   {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Frenemies Scoretracker.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Golf Course Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Course Name</th>
                <th>Total Par</th>
                <th>Last Updated</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                <tr>
                    <td>{{ course.course_name }}</td>
                    <td>{{ course.total_par }}</td>
                    <td>{{ course.updated_date }}</td>
                    {% if request.user|has_group:"Commish" %}
                    <td><a href="{% url 'crm:golf_course_edit' pk=course.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'crm:golf_course_delete' pk=course.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    {% endif %}
                    <td><a href="{% url 'crm:score_compare' pk=course.pk %}"
                           class="btn btn-primary">Score Compare</a>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
         <a href="{% url 'crm:golf_course_new' %}" class="row"><span
                    class="btn btn-primary">Add Golf Course</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/golf_course_new.html
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a Golf Course</h1>
    <form method="POST" class="course-form">{% csrf_token %}
          {{ form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

crm/templates/crm/home.html
{% extends 'crm/base.html' %}
{% load static %}
{% block content %}
    <body>
    <html>
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/Course_photo.jpg" %}" alt="course_photo"/>
                                        <div class="caption">
                                            <h2>Golf Courses</h2>
                                            <p>Courses utilized by Frenemies</p>
                                            <p><a class="btn btn-primary" href="{% url 'crm:golf_course_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/scorecard.jpg" %}" alt="scorecard"/>
                                        <div class="caption">
                                            <h2>My Scores</h2>
                                            <p>Less is more!</p>
                                            <p><a class="btn btn-primary" href="{% url 'crm:score_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </html>
    </body>
{% endblock %}

crm/templates/crm/score_compare.html
{% extends 'crm/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Maverick Food services, Ingredients For Your Success!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h1 style="padding-left: 15Px">Score Summary</h1>
</div>
    <div class="row">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Course</th>
                <th>Golfer</th>
                <th>Hole 1</th>
                <th>Hole 2</th>
                <th>Hole 3</th>
                <th>Hole 4</th>
                <th>Hole 5</th>
                <th>Hole 6</th>
                <th>Hole 7</th>
                <th>Hole 8</th>
                <th>Hole 9</th>
                <th>Hole 10</th>
                <th>Hole 11</th>
                <th>Hole 12</th>
                <th>Hole 13</th>
                <th>Hole 14</th>
                <th>Hole 15</th>
                <th>Hole 16</th>
                <th>Hole 17</th>
                <th>Hole 18</th>
                <th>Total</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% for score in scores %}
                <tr>
                    <td>{{ score.course_name}}</td>
                    <td>{{ score.user}}</td>
                    <td>{{ score.hole_one }}</td>
                    <td>{{ score.hole_two }}</td>
                    <td>{{ score.hole_three}}</td>
                    <td>{{ score.hole_four }}</td>
                    <td>{{ score.hole_five }}</td>
                    <td>{{ score.hole_six }}</td>
                    <td>{{ score.hole_seven }}</td>
                    <td>{{ score.hole_eight}}</td>
                    <td>{{ score.hole_nine}}</td>
                    <td>{{ score.hole_ten}}</td>
                    <td>{{ score.hole_eleven}}</td>
                    <td>{{ score.hole_twelve}}</td>
                    <td>{{ score.hole_thirteen}}</td>
                    <td>{{ score.hole_fourteen}}</td>
                    <td>{{ score.hole_fifteen}}</td>
                    <td>{{ score.hole_sixteen}}</td>
                    <td>{{ score.hole_seventeen}}</td>
                    <td>{{ score.hole_eighteen}}</td>
                    <td>{{ score.total_score}}</td>
                    <td>{{ score.golf_date}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

crm/templates/crm/score_delete.html
{% extends 'crm/base.html' %}
{% block body_block %}
    <h1>Delete {{score.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=score.score_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/score_edit.html
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Edit Score</h1>
    <form method="POST" class="score-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

crm/templates/crm/score_list.html
   {% extends 'crm/base.html' %}
   {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Maverick Food Services</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Frenemies Scoretracker.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Score Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Course Name</th>
                <th>User</th>
                <th>Total Score</th>
                <th>Date Golfed</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for score in scores %}
                <tr>
                    <td>{{ score.course_name }}</td>
                    <td>{{ score.user }}</td>
                    <td>{{ score.total_score }}</td>
                    <td>{{ score.golf_date}}</td>
                    <td><a href="{% url 'crm:score_edit' pk=score.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'crm:score_delete' pk=score.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
         <a href="{% url 'crm:score_new' %}" class="row"><span
                    class="btn btn-primary">Add Score</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/score_new.html
{% extends 'crm/base.html' %}
{% block content %}
    <h1>Add a New Score</h1>
    <form method="POST" class="score-form">{% csrf_token %}
          {{  form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}